version: '3'

networks:
    wp_blog:
        driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/dongchoi/data/wordpress
    mariadb:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/dongchoi/data/mariadb

services:
    mariadb:
        container_name: mariadb
        restart: always
        env_file:
            - .env
        build: ./requirements/mariadb
        image: mariadb
        expose:
            - "3306"
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - wp_blog
    nginx:
        container_name: nginx
        restart: always
        env_file:
            - .env
        build: ./requirements/nginx
        image: nginx
        depends_on:
            - wordpress
        extra_hosts:
            - "dongchoi.42.fr:127.0.0.1"
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - wp_blog
    wordpress:
        container_name: wordpress
        restart: always
        env_file:
            - .env
        build: ./requirements/wordpress
        image: wordpress
        depends_on:
            - mariadb
            - redis
        volumes:
            - wordpress:/var/www/html
        expose:
            - "9000"
        networks:
            - wp_blog
    redis:
        container_name: redis
        restart: always
        env_file:
            - .env
        build: ./requirements/bonus/redis
        image: redis
        volumes:
            - wordpress:/var/www/html
        expose:
            - "6379"
        networks:
            - wp_blog
        tty: true
    ftp:
        container_name: ftp
        restart: always
        env_file:
            - .env
        build: ./requirements/bonus/ftp
        image: ftp
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        expose:
            - "21"
        networks:
            - wp_blog
        tty: true
    adminer:
        container_name: adminer
        restart: always
        env_file:
            - .env
        build: ./requirements/bonus/adminer
        image: adminer
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        expose:
            - "8000"
        networks:
            - wp_blog
    elementor:
        container_name: elementor
        restart: always
        env_file:
            - .env
        build: ./requirements/bonus/elementor
        image: elementor
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        expose:
            - "7000"
        networks:
            - wp_blog